services:
  database:
    image: postgres:17
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "4173:4173"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
