version: '3.8'

services:
  database:
    image: postgres:17
    container_name: bainfullstack-db
    environment:
      POSTGRES_USER: bain_user
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: bainfullstack
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./server
    container_name: bainfullstack-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_USER=bain_user
      - DB_PASSWORD=Password123
      - DB_NAME=bainfullstack
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    image: node:20
    container_name: bainfullstack-frontend
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
